import PageProgress from "@components/atoms/page-progress";
import Anchor from "@components/molecules/anchor";
import IntlProvider from "@core/context/IntlProvider";
import { LenisProvider } from "@core/context/LenisProvider";
import { UIProvider } from "@core/context/ui-provider";
import { routing } from "@core/locale/i18n/routing";
import { selfURL } from "@shared/env";
import { cn } from "@shared/lib/utils";
import "@shared/styles/globals.scss";
import type { Metadata } from "next";
import { hasLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { ReactNode } from "react";

const inter = Inter({
  preload: true,
  subsets: ["latin", "cyrillic"],
  variable: "--font-inter",
  display: "swap",
  fallback: ["system-ui", "arial", "sans-serif"],
});

export async function generateMetadata(): Promise<Metadata> {
  return {
    metadataBase: selfURL ? new URL(selfURL) : null,
    title: "Create Next App",
    description: "Generated by create next app",
  };
}

export function generateStaticParams() {
  return routing.locales.map(locale => ({ locale }));
}

interface RootLayoutProps {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}

async function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) notFound();

  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body
        suppressHydrationWarning
        className={cn(
          inter.className,
          "text-white font-light antialiased text-base"
        )}
      >
        <IntlProvider
          locale={locale}
          messages={messages}
        >
          <LenisProvider>
            <UIProvider>
              {/* <Header /> */}
              {children}
              <PageProgress />
              <Anchor />

              {/* <Footer currentDate={new Date()} /> */}
            </UIProvider>
          </LenisProvider>
        </IntlProvider>
      </body>
    </html>
  );
}

export default RootLayout;
